# Generated by Django 2.2.4 on 2019-08-22 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OreDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.ManyToManyField(blank=True, related_name='_machine_aliases_+', to='craftDB.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=300, verbose_name='Item Name')),
                ('itemid', models.CharField(max_length=300, verbose_name='ID')),
                ('stack', models.IntegerField(default=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)], verbose_name='Stack Size')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Mod', verbose_name='Source Mod')),
                ('oredict', models.ManyToManyField(blank=True, to='craftDB.OreDict', verbose_name='Ore Dictionary')),
            ],
        ),
    ]
