# Generated by Django 2.2.4 on 2019-08-25 03:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=300, verbose_name='Item Name')),
                ('itemid', models.CharField(max_length=300, verbose_name='ID')),
                ('stack', models.IntegerField(default=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)], verbose_name='Stack Size')),
                ('base_resource', models.BooleanField(default=False, verbose_name='Base Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OreDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ore Dictionary',
                'verbose_name_plural': 'Ore Dictionaries',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Amount')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Item', verbose_name='Output')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('aliases', models.ManyToManyField(blank=True, related_name='_machine_aliases_+', to='craftDB.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Mod', verbose_name='Source Mod'),
        ),
        migrations.AddField(
            model_name='item',
            name='oredict',
            field=models.ManyToManyField(blank=True, to='craftDB.OreDict', verbose_name='Ore Dictionary'),
        ),
        migrations.CreateModel(
            name='ByProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Item', verbose_name='Byproduct')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Recipe')),
            ],
            options={
                'verbose_name': 'Byproduct',
                'verbose_name_plural': 'Byproducts',
            },
        ),
        migrations.CreateModel(
            name='MachineRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='craftDB.Recipe')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Machine', verbose_name='Machine')),
            ],
            bases=('craftDB.recipe',),
        ),
        migrations.CreateModel(
            name='MachineInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Item', verbose_name='Input')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.MachineRecipe')),
            ],
        ),
    ]
