# Generated by Django 2.2.4 on 2019-08-25 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftingRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='craftDB.Recipe')),
            ],
            bases=('craftDB.recipe',),
        ),
        migrations.CreateModel(
            name='Slotdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=1, verbose_name='Slot')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Item', verbose_name='Item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.CraftingRecipe')),
            ],
            options={
                'verbose_name': 'Slot Data',
                'verbose_name_plural': 'Slot Data',
            },
        ),
        migrations.CreateModel(
            name='ModPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('mods', models.ManyToManyField(blank=True, to='craftDB.Mod', verbose_name='Mods')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('items', models.ManyToManyField(blank=True, to='craftDB.Item', verbose_name='Items')),
            ],
        ),
    ]
