# Generated by Django 2.2.4 on 2019-08-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Amount')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Item', verbose_name='Output')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='ByProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Item', verbose_name='Byproduct')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Recipe')),
            ],
            options={
                'verbose_name': 'Byproduct',
                'verbose_name_plural': 'Byproducts',
            },
        ),
    ]
