# Generated by Django 2.2.4 on 2019-08-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0002_byproducts_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='craftDB.Recipe')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Machine', verbose_name='Machine')),
            ],
            bases=('craftDB.recipe',),
        ),
        migrations.CreateModel(
            name='MachineInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Item', verbose_name='Input')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.MachineRecipe')),
            ],
        ),
    ]
