# Generated by Django 2.2.4 on 2019-09-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('craftDB', '0002_craftingrecipe_group_modpack_slotdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineinput',
            name='item',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='item',
        ),
        migrations.AddField(
            model_name='machineinput',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='machineinput',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='slotdata',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='slotdata',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
