# Generated by Django 2.2.4 on 2019-09-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0003_auto_20190902_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sprite',
            field=models.ImageField(blank=True, upload_to='sprites/'),
        ),
        migrations.AddField(
            model_name='oredict',
            name='leading_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='craftDB.Item', verbose_name='Representative Item'),
        ),
        migrations.AlterField(
            model_name='machineinput',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'craftDB'), ('model', 'OreDict')), models.Q(('app_label', 'craftDB'), ('model', 'Item')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='slotdata',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'craftDB'), ('model', 'OreDict')), models.Q(('app_label', 'craftDB'), ('model', 'Item')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Item'),
        ),
    ]
