# Generated by Django 2.2.4 on 2019-08-22 18:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0003_machineinput_machinerecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftingRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='craftDB.Recipe')),
            ],
            bases=('craftDB.recipe',),
        ),
        migrations.CreateModel(
            name='Slotdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.CharField(default='1', max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='Slots')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Item', verbose_name='Item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.CraftingRecipe')),
            ],
            options={
                'verbose_name': 'Slot Data',
                'verbose_name_plural': 'Slot Data',
            },
        ),
    ]
