# Generated by Django 2.2.4 on 2019-08-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0004_craftingrecipe_slotdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_resource',
            field=models.BooleanField(default=False, verbose_name='Base Resource'),
        ),
    ]
