# Generated by Django 2.2.4 on 2019-09-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0004_auto_20190903_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sprite',
            field=models.ImageField(default='sprites/default.png', upload_to='sprites/'),
        ),
    ]
