# Generated by Django 2.2.4 on 2019-09-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0005_auto_20190903_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sprite',
            field=models.ImageField(default='default.png', upload_to='sprites/'),
        ),
    ]
